import { bodyWidth, theme } from "../../utils/theme";

export const styles = {
  partnersBackground: {
    position: "absolute",
    right: -1000,
    top: { xs: -1120, sm: -1400 },
    zIndex: -1,
  },
  partnersBodyContainer: {
    alignItems: "center",
    backgroundColor: theme.palette.grays.white,
    display: "flex",
    flexDirection: "column",
    height: "fit-content",
    justifyContent: "center",
    paddingBottom: { xs: theme.spacing(18), sm: theme.spacing(20) },
    paddingTop: { xs: theme.spacing(10), sm: theme.spacing(11) },
    maxWidth: bodyWidth.maxWidth,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  partnersContainer: {
    alignItems: "center",
    display: "flex",
    height: "100%",
    justifyContent: "center",
    position: "relative",
    width: "100%",
  },
  partnerIcon: {
    backgroundColor: "transparent",
    borderRadius: "50%",
    filter: "grayscale(100)",
    height: { xs: 'fit-content', sm: 'fit-content' },
    marginLeft: theme.spacing(4),
    marginRight: theme.spacing(4),
    marginTop: theme.spacing(4),
    opacity: 0.5,
    transition: "all 0.5s ease-in-out",
    width: { xs: 150, sm: 180 },
    "&:hover": {
      filter: "grayscale(0)",
      opacity: 1,
    },
  },
  partnersItems: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  partnersTitle: {
    color: theme.palette.secondary.main,
    fontSize: theme.typography.fontSize * 3,
    fontWeight: 700,
    letterSpacing: 1,
    lineHeight: 1.5,
    marginTop: { xs: theme.spacing(5), sm: theme.spacing(2.5) },
    marginBottom: theme.spacing(3),
  },
  grow: {
    flexGrow: 1,
    marginLeft: "auto",
  },
  margin: {
    display: "flex",
    margin: theme.spacing(1),
  },
};
